import '../styles/globals.css'
import Head from "next/head";
import Layout from '../components/Layout/Layout';
import 'antd/dist/antd.css';
function MyApp({ Component, pageProps }) {
  return <>
  <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
          <Component {...pageProps} />
      </Layout>
  </>
}

export default MyApp
